### ISSUE TITLE
Prohibited terms: master and slave

### ISSUE THREAD

**Issue by cdmauney** [ibm-cloud-docs/virtualization#2]
* master: Do not use. Use another term such as "controller", "leader", "manager", "main", "coordinator", "parent", or "primary [server, node, process, or other noun]".
* slave: Do not use. Use another term such as "worker", "child", "helper", "replica", "follower", or "secondary [server, node, process, or other noun]".

List of topics where terms are used:
* https://cloud.ibm.com/docs/virtualization?topic=virtualization-xenserver-pooling
* https://cloud.ibm.com/docs/virtualization?topic=virtualization-managing-multiple-virtuozzo-hardware-nodes-through-a-single-interface
* https://cloud.ibm.com/docs/virtualization?topic=virtualization-removing-a-host-node-in-pim
* https://cloud.ibm.com/docs/virtualization?topic=virtualization-adding-a-host-node-in-pim

**Comment by bpersich** [comment]
Fixed 10/29
