### ISSUE TITLE
Virtualisation section not updated since 2018

### ISSUE THREAD

**Issue by mark-buckwell** [ibm-cloud-docs/virtualization#4]
This whole section has suddenly appeared and the VPC paged removed. It looks like it's out of date and does not reflect the current sevices. Can you review the whole section and check where the VPC section has gone from [https://cloud.ibm.com/docs?tab=all-docs&category=compute](https://cloud.ibm.com/docs?tab=all-docs&category=compute)

**Comment by gudrun-wolfgram** [comment]
Thanks for your feedack, @markbuckwell. We discussed the changes on Slack.
